begin;

insert into public.vehicle_model_catalog (market, make, model, year_start, year_end, body_type, popularity_rank, image_url, notes)
values
  ('US','Toyota','Tundra',2015,2026,'truck',34,'/catalog/generic-car.svg','Common full-size pickup in US shops.'),
  ('US','Chevrolet','Colorado',2015,2026,'truck',35,'/catalog/generic-car.svg','Common midsize pickup in US shops.'),
  ('US','GMC','Canyon',2015,2026,'truck',36,'/catalog/generic-car.svg','Common midsize pickup in US shops.'),
  ('US','Nissan','Frontier',2015,2026,'truck',37,'/catalog/generic-car.svg','Common midsize pickup in US shops.'),
  ('US','Honda','Ridgeline',2017,2026,'truck',38,'/catalog/generic-car.svg','Common midsize pickup in US shops.'),
  ('US','Jeep','Gladiator',2020,2026,'truck',39,'/catalog/generic-car.svg','Common pickup in US shops.'),
  ('US','Ford','Maverick',2022,2026,'truck',40,'/catalog/generic-car.svg','Common compact pickup in US shops.'),
  ('US','Toyota','4Runner',2015,2026,'suv',41,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Toyota','Corolla Cross',2022,2026,'suv',42,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','Honda','HR-V',2016,2026,'suv',43,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','Honda','Pilot',2015,2026,'suv',44,'/catalog/generic-car.svg','Common midsize SUV in US shops.'),
  ('US','Honda','Passport',2019,2026,'suv',45,'/catalog/generic-car.svg','Common midsize SUV in US shops.'),
  ('US','Nissan','Pathfinder',2015,2026,'suv',46,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Nissan','Murano',2015,2026,'suv',47,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Nissan','Armada',2015,2026,'suv',48,'/catalog/generic-car.svg','Common full-size SUV in US shops.'),
  ('US','Chevrolet','Tahoe',2015,2026,'suv',49,'/catalog/generic-car.svg','Common full-size SUV in US shops.'),
  ('US','Chevrolet','Suburban',2015,2026,'suv',50,'/catalog/generic-car.svg','Common full-size SUV in US shops.'),
  ('US','Chevrolet','Traverse',2015,2026,'suv',51,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Chevrolet','Blazer',2019,2026,'suv',52,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Chevrolet','Trailblazer',2021,2026,'suv',53,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','Jeep','Wrangler',2015,2026,'suv',54,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Jeep','Compass',2015,2026,'suv',55,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','Jeep','Cherokee',2015,2023,'suv',56,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Jeep','Wagoneer',2022,2026,'suv',57,'/catalog/generic-car.svg','Common full-size SUV in US shops.'),
  ('US','Ford','Expedition',2015,2026,'suv',58,'/catalog/generic-car.svg','Common full-size SUV in US shops.'),
  ('US','Ford','Bronco',2021,2026,'suv',59,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Ford','Bronco Sport',2021,2026,'suv',60,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','Ford','Edge',2015,2024,'suv',61,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Toyota','Sequoia',2015,2026,'suv',62,'/catalog/generic-car.svg','Common full-size SUV in US shops.'),
  ('US','Hyundai','Palisade',2020,2026,'suv',63,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Hyundai','Kona',2018,2026,'suv',64,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','Kia','Sorento',2015,2026,'suv',65,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Kia','Seltos',2021,2026,'suv',66,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','Subaru','Crosstrek',2015,2026,'suv',67,'/catalog/generic-car.svg','Common crossover in US shops.'),
  ('US','Subaru','Ascent',2019,2026,'suv',68,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Mazda','CX-30',2020,2026,'suv',69,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','Mazda','CX-50',2023,2026,'suv',70,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Mazda','CX-90',2024,2026,'suv',71,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Mitsubishi','Outlander Sport',2015,2026,'suv',72,'/catalog/generic-car.svg','Common compact SUV in US shops.'),
  ('US','GMC','Terrain',2015,2026,'suv',73,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','GMC','Acadia',2015,2026,'suv',74,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','GMC','Yukon',2015,2026,'suv',75,'/catalog/generic-car.svg','Common full-size SUV in US shops.'),
  ('US','Buick','Enclave',2015,2026,'suv',76,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Cadillac','XT5',2017,2026,'suv',77,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Lincoln','Aviator',2020,2026,'suv',78,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Lincoln','Nautilus',2019,2026,'suv',79,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Lexus','NX',2015,2026,'suv',80,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Lexus','GX',2015,2026,'suv',81,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Acura','RDX',2015,2026,'suv',82,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','Infiniti','QX80',2015,2026,'suv',83,'/catalog/generic-car.svg','Common full-size SUV in US shops.'),
  ('US','Volvo','XC60',2015,2026,'suv',84,'/catalog/generic-car.svg','Common SUV in US shops.'),
  ('US','BMW','X3',2015,2026,'suv',85,'/catalog/generic-car.svg','Common premium SUV in US shops.'),
  ('US','BMW','X5',2015,2026,'suv',86,'/catalog/generic-car.svg','Common premium SUV in US shops.'),
  ('US','Mercedes-Benz','GLC',2016,2026,'suv',87,'/catalog/generic-car.svg','Common premium SUV in US shops.'),
  ('US','Mercedes-Benz','GLE',2016,2026,'suv',88,'/catalog/generic-car.svg','Common premium SUV in US shops.'),
  ('US','Audi','Q5',2015,2026,'suv',89,'/catalog/generic-car.svg','Common premium SUV in US shops.'),
  ('US','Audi','Q7',2015,2026,'suv',90,'/catalog/generic-car.svg','Common premium SUV in US shops.'),
  ('US','Porsche','Macan',2015,2026,'suv',91,'/catalog/generic-car.svg','Common premium SUV in US shops.'),
  ('US','Tesla','Model X',2016,2026,'ev',92,'/catalog/generic-car.svg','Common electric SUV in US shops.'),
  ('US','Toyota','Avalon',2015,2022,'sedan',93,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','Toyota','Crown',2023,2026,'sedan',94,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','Toyota','Prius',2015,2026,'hatchback',95,'/catalog/generic-car.svg','Common hybrid hatchback in US shops.'),
  ('US','Nissan','Versa',2015,2026,'sedan',96,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','Nissan','Maxima',2015,2023,'sedan',97,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','Hyundai','Sonata',2015,2026,'sedan',98,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','Volkswagen','Passat',2015,2022,'sedan',99,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','BMW','330i',2019,2026,'sedan',100,'/catalog/generic-car.svg','Common premium sedan in US shops.'),
  ('US','BMW','530i',2017,2026,'sedan',101,'/catalog/generic-car.svg','Common premium sedan in US shops.'),
  ('US','Mercedes-Benz','E-Class',2015,2026,'sedan',102,'/catalog/generic-car.svg','Common premium sedan in US shops.'),
  ('US','Audi','A6',2015,2026,'sedan',103,'/catalog/generic-car.svg','Common premium sedan in US shops.'),
  ('US','Lexus','IS',2015,2026,'sedan',104,'/catalog/generic-car.svg','Common premium sedan in US shops.'),
  ('US','Acura','Integra',2023,2026,'hatchback',105,'/catalog/generic-car.svg','Common hatchback in US shops.'),
  ('US','Kia','Forte',2015,2026,'sedan',106,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','Dodge','Charger',2015,2023,'sedan',107,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','Chrysler','300',2015,2023,'sedan',108,'/catalog/generic-car.svg','Common sedan in US shops.'),
  ('US','Tesla','Model S',2015,2026,'ev',109,'/catalog/generic-car.svg','Common electric sedan in US shops.'),
  ('US','Kia','Soul',2015,2026,'hatchback',110,'/catalog/generic-car.svg','Common hatchback in US shops.'),
  ('US','Chevrolet','Bolt EV',2017,2023,'ev',111,'/catalog/generic-car.svg','Common electric hatchback in US shops.'),
  ('US','Chevrolet','Corvette',2015,2026,'coupe',112,'/catalog/generic-car.svg','Common performance coupe in US shops.'),
  ('US','Kia','Carnival',2022,2026,'van',113,'/catalog/generic-car.svg','Common minivan in US shops.'),
  ('US','Dodge','Grand Caravan',2015,2020,'van',114,'/catalog/generic-car.svg','Common minivan in US shops.')
on conflict (market, make, model, year_start, year_end) do update
set body_type = excluded.body_type,
    popularity_rank = excluded.popularity_rank,
    image_url = excluded.image_url,
    notes = excluded.notes;

update public.vehicles v
set catalog_model_id = c.id
from public.vehicle_model_catalog c
where v.catalog_model_id is null
  and lower(v.make) = lower(c.make)
  and lower(v.model) = lower(c.model);

commit;
